### ISSUE TITLE
Renaming fails

### ISSUE THREAD

**Issue by philholden** [FormidableLabs/generator-formidable-react-component#25]
Tried creating a component called Button `yo formidable-react-component` but get following error: 

``` bash
renaming files

could not rename /Users/ph185068/experimental/formidable/button/src/components/boilerplate-component.jsx

renaming test files

/Users/ph185068/experimental/formidable/button/test/client/button/components/boilerplate-component.spec.jsx
```

I am using `nvm` on Mac same thing happens for victory and non victory components. Tried:

 `sudo yo formidable-react-component`

Also get same error

**Comment by ryan-roemer** [comment]
@boygirl - can you take a look? Thanks!

**Comment by boygirl** [comment]
@philholden I forgot to actually _publish_ our latest round of changes! I just remedied the situation, so if you install the latest version `generator-formidable-react-component@1.2.0` and try again it should work.

**Comment by philholden** [comment]
Thanks I really love the project. I am trying to persuade folks at work to go with this rather than Bootstrap for our UI.

If I want to create small components like buttons I'd still like each component to be importable independently. So I like the idea of one module per component. However I think I might run out of disk space because each npm install takes 300M on disk. Is there some way I can get round this with builder? 

How do I go about structuring a component library - lots of repos or one?

What is the difference between a victory and a react component? (is it just Radium)

**Comment by boygirl** [comment]
@philholden we're been taking the one repo per component approach, which is why the generators / boilerplates are such a life saver! As for disk space, if you're using npm 3 and all of your components are based on the same boilerplate, npm should dedupe a lot of those repeated dependencies. We're still working some of the kinks in builder, so if that is _not_ the case with builder projects for some reason, we will figure that out soon.  Speaking of builder... it will soon be responsible for generating boilerplate projects instead of this yeoman generator, so look forward to that.

victory is an open source data viz initiative we're working on.  So far the infrastructure for victory components hasn't diverged very much from our regular react components, but we wrote this generator with that in mind.

**Comment by philholden** [comment]
Hi I am now getting the following error when I do:

``` bash
$ builder run dev

[builder:config:environment] {"cwd":"/Users/ph185068/personal/subtitle-ui/song-chooser","dir":"/Users/ph185068/personal/subtitle-ui/song-chooser/node_modules/builder/lib"}
[builder:run] dev - builder concurrent server-dev server-test
[builder:proc:start] builder concurrent server-dev server-test
[builder:config:environment] {"cwd":"/Users/ph185068/personal/subtitle-ui/song-chooser","dir":"/Users/ph185068/personal/subtitle-ui/song-chooser/node_modules/builder/lib"}
[builder:concurrent] server-dev, server-test
 * server-dev - webpack-dev-server --port 3000 --config node_modules/builder-react-component/config/webpack/demo/webpack.config.dev.js --colors --content-base demo
 * server-test - webpack-dev-server --port 3001 --config node_modules/builder-react-component/config/webpack/webpack.config.test.js --colors
[builder:proc:start] webpack-dev-server --port 3000 --config node_modules/builder-react-component/config/webpack/demo/webpack.config.dev.js --colors --content-base demo
[builder:proc:start] webpack-dev-server --port 3001 --config node_modules/builder-react-component/config/webpack/webpack.config.test.js --colors
/bin/sh: webpack-dev-server: command not found
/bin/sh: webpack-dev-server: command not found
[builder:proc:error] Code: 127, Command: webpack-dev-server --port 3000 --config node_modules/builder-react-component/config/webpack/demo/webpack.config.dev.js --colors --content-base demo
[builder:proc:end:127] webpack-dev-server --port 3000 --config node_modules/builder-react-component/config/webpack/demo/webpack.config.dev.js --colors --content-base demo
[builder:proc:error] Code: 127, Command: builder concurrent server-dev server-test
[builder:proc:end:127] builder concurrent server-dev server-test
```

I am now using node 5 and npm 3.

**Comment by ryan-roemer** [comment]
@philholden -- I'm not sure when you generated, but it looks like you're missing the dev dependencies. Can you install the latest iterations of both:

```
$ npm install --save builder-react-component@0.1.1
$ npm install --save-dev builder-react-component-dev@0.1.1
```

and see if that works? (The `-dev` module has all the dev dependencies like `webpack-dev-server`)

**Comment by philholden** [comment]
@ryan-roemer Thanks that worked. However I generated 2 hours ago and the generator was a fresh install too.

Am I right in thinking the generator does not give boilerplate for ecology docs?

I've done a private screencast on Victory. It is private as it relates to a discussion at my work, but plan to record a public facing version so would welcome feedback.

https://www.youtube.com/watch?v=uKBpTx0ZW8c

One of the things I don't really understand is how to use builder to streamline multiple repositories with identical/similar dependencies. It sound like I can have a master project and have other projects inherit node_modules without doing a full install is this correct? If so how do I do it? I'd really appreciate an example of working with two similar repos.

Suppose I wanted one repo for a `button` and another for a `link` and both projects had the same workflow and dependencies. How do I use builder so the projects can share as much as infrastructure as possible? (I could not work this out from the docs)

Thanks

**Comment by ryan-roemer** [comment]
@philholden -- @boygirl can help you more with the generator and ecology and such.

As for builder and multiple repos, it's really a matter of having one archetype that defines your prod (e.g. `builder-react-component`) and dev (e.g., `builder-react-component-dev`) tasks and dependencies.

Then your apps just depend on something like this:

``` js
  "dependencies": {
    "builder": "2.1.0",
    "builder-react-component": "0.1.1"
  },
  "devDependencies": {
    "builder-react-component-dev": "0.1.1"
  }
```

and that's it for individual projects. You control all further tasks, dependencies, etc. through the upstream archetype repositories.

In your case, I'm guessing you could create something close to `builder-react-component` for your set of related repos and go from there.

**Comment by boygirl** [comment]
@philholden I just pushed to the `victory-component-boilerplate`. I didn't realize anyone outside of our org was using that yet! As for the ecology stuff. There are definitely plans for including ecology boilerplate for generated victory components, but not for regular react components. This work will be done in the next couple weeks, but we will also be switching to use builder for generating components rather than yeoman. As soon as we're able to land template functionality in builder, active development of this generator will taper off pretty quickly

I wasn't able to view the youtube link you included, but please reach out to me if you have any questions about using victory.

**Comment by philholden** [comment]
@boygirl sorry I did not press save on the video after changing it to unlisted so it was set to private it is now available: https://youtu.be/uKBpTx0ZW8c

Moving up to NPM 3 has cut the size of each repo down to about 100MB. I think NPM is deduping within a single repo rather than between multiple repos in dev. I can see you get a deduping effect when you install two components into another project that uses them. I am wanting to dedupe in dev when I am working on 50 small components. I am wondering if I can install archetypes globally?

> I didn't realize anyone outside of our org was using that yet!

I think Ecology, Builder & Victory meets a real need. Really like Radium and now trying to develop two different component libraries:
1. Spike a Bootstrap replacement for my work that allows clients to customise UI. So Ecology looks good for this but our components are much smaller than for victory. So 100MB for a checkbox or a label is still quite big. After using Radium I don't want to back to Bootstrap.
2. Subdivide: Allows users to split browser windows into panes and assign a different component to each pane. I want to create a component ecosystem for it. A bit like Victory most component will be quite large:
   
   https://www.youtube.com/watch?v=3ePrvrx9otk
   
   This project should work really well for Victory for dashboards etc

As a newcomer to Victory, Builder and Ecology it is quite hard to find where to start, because there are so many repos and the docs are spread between them. So it is hard to know where to start and what the next step is. It would be helpful if there was a getting started guide that covered the ecosystem and could be referenced in each repo. I'd be happy to contribute. Something like the Redux docs would be great even if it started as an intro section that had a title and a blank page.

**Comment by boygirl** [comment]
@philholden thanks for the excellent video! 

We're definitely in need of a getting started guide to the ecosystem; we've sort of been holding off until a few builder features land. With the project getting more attention, I think you're right that just getting a "coming soon" page up is a good idea.

As for the component size, we'll work on getting that down. Right now we're depending on _all_ of d3. When we started the d3 modules were a little shakey, but I think they've improved enough for us to start depending on them individually. 

Subdivide looks excellent! I can definitely imagine using it with Victory. Maybe we'll get to collaborate in the future.
